CREATE DATABASE farmdb;

USE farmdb;

SHOW TABLES;

SELECT * FROM USER;

SELECT * FROM USER WHERE ROLE = "FARMER";

SELECT * FROM USER WHERE ROLE = "INSPECTOR";

SELECT * FROM USER WHERE ROLE = "PROCUREMENT";

SELECT * FROM USER WHERE ROLE = "ADMIN";